### PR TITLE
Add Unraid community application template

### PR DESCRIPTION
**Pull request by mattwebbio**

### CODE REVIEW

**Comment by B0rax** [comment]
Is there something we can do to get this merged?

**Comment by mattwebbio** [comment]
@B0rax 
> Is there something we can do to get this merged?

I wasn't immediately able to figure out how to test this or get it added to the Community Applications repository, so I'm not actually sure if it works as written. If you could figure either of those things out, that would be great :smile:

**Comment by TheReclusiveFox** [comment]
To test it locally you can follow Squid's comment here:
https://forums.unraid.net/topic/55503-how-to-submit-new-docker-containers-to-community-apps/?do=findComment&comment=836960

He also links to the process to submitting to CA officially. I just tried the local method and template looks good to me 🙂

**Comment by fletchto99** [comment]
@mattwebbio you can also submit it to the selfhosters repo: https://github.com/selfhosters/unRAID-CA-templates/tree/master/templates

This is where I sent my templates and they were populated in the unraid CA

**Comment by twistedgrim** [comment]
Looks like this works great. Just tried it and migrated my orbital sync container! Thanks!

**Comment by mattwebbio** [comment]
@twistedgrim 
> Looks like this works great. Just tried it and migrated my orbital sync container! Thanks!

Thanks for testing this! I'll go ahead and try creating a PR to [selfhosters/unRAID-CA-templates](https://github.com/selfhosters/unRAID-CA-templates/tree/master/templates) like @fletchto99 suggested

**Comment by mattwebbio** [comment]
PR created; closing and further conversation can move over there:
https://github.com/selfhosters/unRAID-CA-templates/pull/473

**Pull request closed without merging**
